name: Unit tests
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Build and test with Rake
      run: |
        sudo apt-get -yqq install libpq-dev
        bundle install --jobs 4 --retry 3
        bundle exec rake test:coverage 
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

